import type { Metadata } from 'next';
import { Space_Grotesk, Poppins, Josefin_Sans } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import CurrentUserProvider from '@/context/user-context/CurrentUserProvider';
import { Toaster } from 'react-hot-toast';
import { getCurrentUser } from '@/lib/auth/getCurrentUser';
import ImageProvider from '@/context/imagesContext/ImageProvider';

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700', '800'],
});

const space_grotesk = Space_Grotesk({
    variable: '--font-space',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600'],
});

const josefin_sans = Josefin_Sans({
    variable: '--font-josefin',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getCurrentUser();

    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className={`${poppins.variable} ${space_grotesk.variable} ${josefin_sans.variable} antialiased bg-background`}
                >
                    <Toaster position="top-center" reverseOrder={false} />
                    <CurrentUserProvider currentUser={user}>
                        <ImageProvider>{children}</ImageProvider>
                    </CurrentUserProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
